openstack overcloud container image prepare \
  --namespace=docker-registry.engineering.redhat.com/rhosp13 \
  --push-destination=192.168.24.1:8787 \
  --prefix=openstack- \
  --tag=latest \
  --output-env-file=/home/stack/templates/environments/overcloud-images.yaml \
  --output-images-file /home/stack/local-registry-images.yaml \
  -r -r {ENVIRONMENTS}/roles_data.yaml \
  -e /usr/share/openstack-tripleo-heat-templates/environments/ceph-ansible/ceph-ansible.yaml \
  -e /usr/share/openstack-tripleo-heat-templates/environments/services-docker/neutron-sriov.yaml \
  --set ceph_namespace=registry.access.redhat.com/rhceph \
  --set ceph_image=rhceph-3-rhel7 \
  --set ceph_tag=latest
